# Standards: 0.1
---
- name: Fact steam user
  set_fact:
    steam_user: "{{ steam_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - steam

- become: "{{ (steam_user != ansible_user_id) | bool }}"
  become_user: "{{ steam_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: steam
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - steam

    - name: Remove quarantine flag
      register: steam_quarantine
      failed_when: steam_quarantine.rc != 0 and "No such xattr" not in steam_quarantine.stderr
      changed_when: steam_quarantine.rc == 0
      command: xattr -d com.apple.quarantine /Applications/Steam.app
      tags:
        - steam

    - name: Install pidof package
      homebrew:
        name: pidof
      tags:
        - steam

    - name: Check program running
      register: steam_running
      check_mode: False
      failed_when: False
      changed_when: steam_running.stdout | length > 0 | bool
      command: pidof Steam
      tags:
        - steam

    - name: Fact program running
      set_fact:
        steam_started: "{{ steam_running.stdout_lines | length > 0 | bool }}"
      tags:
        - steam

...
